version: '3.7'

volumes:
  postgres-data:
  ecs-sync:
    external: true
  # encryptor-sync:
  #   external: true
  eventstore-volume-data:
  eventstore-volume-logs:
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  eventstore.db:
    image: eventstore/eventstore:20.6.1-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 1113:1113
      - 1114:1114
      - 2113:2113
      - 2114:2114
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  # encryptor: # PORT 3002
  #   image: yousty/encryptor:dev
  #   command: sh scripts/start_server_dev.sh
  #   volumes:
  #     - /usr/src/app/tmp
  #     - encryptor-sync:/usr/src/app:nocopy
  #   ports:
  #     - "3003:3000"
  #   depends_on:
  #     - db
  #     - eventstore.db
  #   env_file:
  #     - .env_encryptor #this is relative to docker folder

  # specs:
  #   image: yousty/ecs:test
  #   command: tail -f /dev/null
  #   volumes:
  #     - /usr/src/app/tmp
  #     - ecs-sync:/usr/src/app:nocopy
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env_test
